services:
  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data
    # No ports exposed to host
    networks:
      - crawler-net

  kleinanzeigen-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: "Europe/Berlin"
      PORT: 5555
    ports:
      - "5555:5555"
    networks:
      - crawler-net
    secrets:
      - GMAIL_PASS
    command: node ./lib/main.mjs

networks:
  crawler-net:
    driver: bridge
secrets:
  GMAIL_PASS:
    file: ./secrets/GMAIL_PASS
