services:
  valkey:
    ports:
      - "6379:6379"
  worker:
    command: node ./lib/worker.ts --watch
    volumes:
      - ./lib:/app/lib
  frontend:
    command: yarn vite dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
