services:
  valkey:
    volumes:
      - ./data/valkey:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    image: valkey/valkey:9-alpine
    networks:
      - kc-internal
    healthcheck:
      test: ["CMD", "valkey-cli", "--raw", "incr", "ping"]
  mongodb:
    image: mongo:8
    volumes:
      - "./data/mongodb:/data/db"
    user: "1000:1000"
    networks:
      - kc-internal
    command: ["mongod", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGODB_ROOT_PASSWORD
    secrets:
      - MONGODB_ROOT_PASSWORD
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: node ./lib/worker.ts
    env_file: .env
    environment:
      GMAIL_PASS_FILE: /run/secrets/GMAIL_PASS
      MONGODB_CONNECTION_STRING_FILE: /run/secrets/MONGODB_CONNECTION_STRING
    secrets:
      - GMAIL_PASS
      - MONGODB_CONNECTION_STRING
    networks:
      - kc-internal
    depends_on:
      valkey:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    env_file: .env
    environment:
      AUTH_SECRET_FILE: /run/secrets/AUTH_SECRET
      OAUTH_CLIENT_SECRET_FILE: /run/secrets/OAUTH_CLIENT_SECRET
      MONGODB_CONNECTION_STRING_FILE: /run/secrets/MONGODB_CONNECTION_STRING
    secrets:
      - AUTH_SECRET
      - OAUTH_CLIENT_SECRET
      - MONGODB_CONNECTION_STRING
    networks:
      - kc-internal
    depends_on:
      valkey:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
secrets:
  GMAIL_PASS:
    file: ./secrets/GMAIL_PASS
  AUTH_SECRET:
    file: ./secrets/AUTH_SECRET
  OAUTH_CLIENT_SECRET:
    file: ./secrets/OAUTH_CLIENT_SECRET
  MONGODB_CONNECTION_STRING:
    file: ./secrets/MONGODB_CONNECTION_STRING
  MONGODB_ROOT_PASSWORD:
    file: ./secrets/MONGODB_ROOT_PASSWORD
networks:
  kc-internal:
    driver: bridge
