services:
  valkey:
    volumes:
      - ./data/valkey:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    image: valkey/valkey:9-alpine
    networks:
      - kc-internal
    healthcheck:
      test: ["CMD", "valkey-cli", "--raw", "incr", "ping"]
  mongodb:
    image: mongo:8
    volumes:
      - "./data/mongdb:/data/db"
    user: "1000:1000"
    networks:
      - kc-internal
    command: ["mongod", "--bind_ip_all", "--noauth"]
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: node ./lib/worker.ts
    env_file: .env
    environment:
      GMAIL_PASS_FILE: /run/secrets/GMAIL_PASS
      MONGODB_CONNECTION_STRING: mongodb://mongodb:27017/
    secrets:
      - GMAIL_PASS
    networks:
      - kc-internal
    depends_on:
      - valkey
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    env_file: .env
    environment:
      AUTH_SECRET_FILE: /run/secrets/AUTH_SECRET
      OAUTH_CLIENT_SECRET_FILE: /run/secrets/OAUTH_CLIENT_SECRET
    secrets:
      - AUTH_SECRET
      - OAUTH_CLIENT_SECRET
    networks:
      - kc-internal
    depends_on:
      - valkey
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
secrets:
  GMAIL_PASS:
    file: ./secrets/GMAIL_PASS
  AUTH_SECRET:
    file: ./secrets/AUTH_SECRET
  OAUTH_CLIENT_SECRET:
    file: ./secrets/OAUTH_CLIENT_SECRET
networks:
  kc-internal:
    driver: bridge
