services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    # No ports exposed to host
    networks:
      - crawler-net

  kleinanzeigen-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kleinanzeigen-crawler
    env_file: .env
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - crawler-net
    secrets:
      - GMAIL_PASS

networks:
  crawler-net:
    driver: bridge
secrets:
  GMAIL_PASS:
    file: ./secrets/GMAIL_PASS
