import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
  server: {
    PORT: z.coerce.number().default(5555),
    /**
     * This secret is configured via a Docker Secret, the env var itself is just
     * a file handle.
     * 
     * The secret itself can be generated by:

     * openssl rand -hex 32
     */
    AUTH_SECRET_FILE: z.string().nonempty(),
    OAUTH_CLIENT_ID: z.string().nonempty(),
    OAUTH_CLIENT_SECRET_FILE: z.string().nonempty(),
    OAUTH_ISSUER: z.string().nonempty(),
    BETTER_AUTH_TRUSTED_ORIGINS: z.string().trim().optional(),
    BASE_URL: z.url().nonempty(),
    VALKEY_HOST: z.string().nonempty(),
  },

  /**
   * What object holds the environment variables at runtime. This is usually
   * `process.env` or `import.meta.env`.
   */
  runtimeEnv: process.env,

  /**
   * By default, this library will feed the environment variables directly to
   * the Zod validator.
   *
   * This means that if you have an empty string for a value that is supposed
   * to be a number (e.g. `PORT=` in a ".env" file), Zod will incorrectly flag
   * it as a type mismatch violation. Additionally, if you have an empty string
   * for a value that is supposed to be a string with a default value (e.g.
   * `DOMAIN=` in an ".env" file), the default value will never be applied.
   *
   * In order to solve these issues, we recommend that all new projects
   * explicitly specify this option as true.
   */
  emptyStringAsUndefined: true,
});
