/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/_layout'
import { Route as protectedLayoutIndexRouteImport } from './routes/(protected)/_layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as protectedLayoutBrowseRouteImport } from './routes/(protected)/_layout/browse'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutBrowseRoute = protectedLayoutBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => protectedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/browse': typeof protectedLayoutBrowseRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof protectedLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/browse': typeof protectedLayoutBrowseRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof protectedLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/(protected)/_layout': typeof protectedLayoutRouteWithChildren
  '/(protected)/_layout/browse': typeof protectedLayoutBrowseRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/browse' | '/api/auth/$' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/browse' | '/api/auth/$' | '/'
  id:
    | '__root__'
    | '/login'
    | '/(protected)/_layout'
    | '/(protected)/_layout/browse'
    | '/api/auth/$'
    | '/(protected)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/browse': {
      id: '/(protected)/_layout/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof protectedLayoutBrowseRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedLayoutBrowseRoute: typeof protectedLayoutBrowseRoute
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedLayoutBrowseRoute: protectedLayoutBrowseRoute,
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
